---
title: "Análisis Exploratorio, HDT 1"
author: "Ayleen Rubio 19003, Andrés Say 19705. Andreé Toledo 18439"
date: "4/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir="C:/Users/andre/OneDrive/Documentos/HT1.Analisis-Exploratorio")
```

# Informe de análisis exploratorio 
En este informe usted podrá leer los hallazgos de EDA, a continuación se muestra el resumen de los datos:

```{r movies, echo=FALSE}
sum_movies <- read.csv("tmdb-movies.csv")
summary(sum_movies)
```

En el siguiente cuadro se muestra el tipo de dato de cada variable:

```{r data, echo=FALSE}
str(sum_movies)
```
## Prueba de normalidad para datos cuantitativos  

### Prueba de normalidad para popularity:
```{r normal, echo=FALSE}
#install.packages("ggplot2",repos = "http://cran.us.r-project.org")
library (ggplot2)
ggplot(data = sum_movies, aes(x = popularity)) + 
  geom_histogram(aes(y=..density.., fill = ..count..))+
  scale_fill_gradient(low = "#DCDCDC", high = "#7C7C7C")+
  stat_function(fun = dnorm, colour = "firebrick",
                args = list(mean = mean(sum_movies$popularity),
                            sd = sd(sum_movies$popularity)))+
  ggtitle("Histograma con curva normal teórica de la popularidad") + 
  theme_bw()
boxplot(sum_movies$popularity, main = "Caja y Bigotes de Popularidad", xlab = "Popularidad")
qqnorm(sum_movies$popularity, col="blue")
qqline(sum_movies$popularity, col="red")

```




